export interface ProofMetadata {
  /** The unique proof ID generated by the ZK prover */
  proofId: string;
  
  /** The transaction hash representing registration on the Midnight Network ledger */
  midnightTxHash: string;
  
  /** Timestamp indicating ledger confirmation */
  anchoredAt: string;
  
  /** The cryptographic compiler standard identifier used */
  proverVersion: string;
  
  /** Name of the target repository */
  repoName: string;
}

export interface VerificationResult {
  /** True if the proof hash was validated on-chain without alteration */
  isValid: boolean;
  
  /** Array of metrics the startup chose to selectively disclose */
  disclosedItems: string[];
  
  /** The transaction timestamp verified from Midnight Network state */
  timestamp: string;
}
